export const mockMovies = [
  {
    id: 1,
    title: "Inception",
    overview:
      "A skilled thief is offered a chance to erase his criminal history by performing inception: planting an idea into a target's subconscious.",
    poster_path: "images/post1.png",
    backdrop_path: "images/Feature1.png",
    release_date: "2010-07-16",
    vote_average: 8.8,
    vote_count: 32000,
    popularity: 95.5,
    genre_ids: [28, 878, 12],
    original_language: "en",
  },
  {
    id: 2,
    title: "The Dark Knight",
    overview:
      "Batman sets out to dismantle the remaining criminal organizations in Gotham, but finds himself facing the anarchistic Joker.",
    poster_path: "images/post2.png",
    backdrop_path: "images/Feature2.png",
    release_date: "2008-07-18",
    vote_average: 9.0,
    vote_count: 45000,
    popularity: 99.3,
    genre_ids: [28, 80, 18],
    original_language: "en",
  },
  {
    id: 3,
    title: "Interstellar",
    overview:
      "A group of explorers travel through a wormhole in space in an attempt to ensure humanity’s survival.",
    poster_path: "images/post3.png",
    backdrop_path: "images/Feature3.png",
    release_date: "2014-11-07",
    vote_average: 8.6,
    vote_count: 29000,
    popularity: 92.7,
    genre_ids: [12, 18, 878],
    original_language: "en",
  },
  {
    id: 4,
    title: "Parasite",
    overview:
      "A poor family schemes to become employed by a wealthy household and infiltrate their lives with unexpected consequences.",
    poster_path: "images/post4.png",
    backdrop_path: "images/Feature1.png",
    release_date: "2019-05-30",
    vote_average: 8.5,
    vote_count: 18000,
    popularity: 88.1,
    genre_ids: [35, 18, 53],
    original_language: "ko",
  },
  {
    id: 5,
    title: "Avengers: Endgame",
    overview:
      "After the devastating events of Infinity War, the Avengers assemble once more to reverse Thanos' actions and restore balance.",
    poster_path: "images/post5.png",
    backdrop_path: "images/Feature2.png",
    release_date: "2019-04-26",
    vote_average: 8.4,
    vote_count: 50000,
    popularity: 100.0,
    genre_ids: [28, 12, 878],
    original_language: "en",
  },
  {
    id: 6,
    title: "The Matrix",
    overview:
      "A computer hacker learns from mysterious rebels about the true nature of reality and his role in the war against its controllers.",
    poster_path: "images/post6.png",
    backdrop_path: "images/Feature3.png",
    release_date: "1999-03-31",
    vote_average: 8.7,
    vote_count: 21000,
    popularity: 89.4,
    genre_ids: [28, 878],
    original_language: "en",
  },
  {
    id: 7,
    title: "Fight Club",
    overview:
      "An insomniac office worker and a soap salesman form an underground fight club that evolves into something far more dangerous.",
    poster_path: "images/post7.png",
    backdrop_path: "images/Feature1.png",
    release_date: "1999-10-15",
    vote_average: 8.8,
    vote_count: 24000,
    popularity: 86.9,
    genre_ids: [18],
    original_language: "en",
  },
  {
    id: 8,
    title: "The Godfather",
    overview:
      "An organized crime dynasty’s aging patriarch transfers control of his empire to his reluctant son.",
    poster_path: "images/post8.png",
    backdrop_path: "images/Feature2.png",
    release_date: "1972-03-24",
    vote_average: 9.2,
    vote_count: 30000,
    popularity: 85.3,
    genre_ids: [80, 18],
    original_language: "en",
  },
  {
    id: 9,
    title: "Joker",
    overview:
      "A failed stand-up comedian spirals into madness as he becomes the infamous criminal mastermind known as the Joker.",
    poster_path: "images/post9.png",
    backdrop_path: "images/Feature3.png",
    release_date: "2019-10-04",
    vote_average: 8.4,
    vote_count: 22000,
    popularity: 94.8,
    genre_ids: [80, 18, 53],
    original_language: "en",
  },
  {
    id: 10,
    title: "Spirited Away",
    overview:
      "A young girl enters a world ruled by gods, witches, and spirits, where humans are changed into beasts.",
    poster_path: "images/post10.png",
    backdrop_path: "images/Feature1.png",
    release_date: "2001-07-20",
    vote_average: 8.5,
    vote_count: 19000,
    popularity: 90.2,
    genre_ids: [16, 14, 10751],
    original_language: "ja",
  },
];
